#!/usr/bin/env python3
"""Stage 3: Deutsch — Beginning of Infinity. Symbolic scenes only (living author, no portraits).
Run from repo root."""
import argparse, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from gen_infographics import STYLE, gen

OUTDIR = Path("docs/books/beginning-of-infinity/infographics")

# 'episode' = a symbolic scene (NO people/portraits). 'idea_caption' = the concept label.
CH = [
    dict(slug="ch-01-reach-of-explanations", num=1, title="The Reach of Explanations",
         move="Prefer Explanations Hard to Vary",
         problem="an arbitrary mythic scene of a goddess causing winter, every element easily swappable, dissolving",
         problem_labels=["Easy to vary", "Explains nothing"],
         episode="a tilted globe orbiting the sun, geometry forcing opposite seasons in opposite hemispheres",
         idea_caption="Axial tilt: hard to vary",
         stakes_labels=["Self-deception", "No reach"],
         arc=("Fits-the-data", "Hard to vary", "Unlimited reach"),
         lesson="Hard-to-vary explanations track reality", outcome="Good explanations reach far beyond their origin",
         strategies=["Run the variability test", "Make details load-bearing", "Prize reach",
                     "Conjecture then criticize", "Distrust just-so stories", "Seek unexpected solutions"],
         warnings=["Explains the opposite too", "Swappable details", "Empiricist reflexes", "No reach"]),
    dict(slug="ch-02-closer-to-reality", num=2, title="Closer to Reality",
         move="Trust the Better Inference Chain",
         problem="a lone eye squinting at a faint blur, mistaking rawness for directness",
         problem_labels=["Naked eye", "Less faithful"],
         episode="a telescope-to-screen pipeline rendering a vivid galaxy, each stage a rung of theory",
         idea_caption="Instruments as inference chains",
         stakes_labels=["Gut over data", "Hidden bugs"],
         arc=("Unaided eye trusted", "Audit the chain", "More direct via theory"),
         lesson="All perception is theory-laden inference", outcome="Better chains bring us closer to reality",
         strategies=["Audit the pipeline", "Criticize each stage", "Doubt eyewitness too",
                     "Trust good instruments", "Name embedded theories", "Improve the chain"],
         warnings=["Directness worship", "Unaudited metrics", "I-saw-it-myself", "Stale pipeline theory"]),
    dict(slug="ch-03-the-spark", num=3, title="The Spark",
         move="Treat Limits as Knowledge Problems",
         problem="a tiny figure labeled insignificant crouched on a rock under a vast dismissive cosmos",
         problem_labels=["Mediocrity myth", "Spaceship Earth"],
         episode="a cold barren landscape transformed by fire, shelter, and tools into a thriving settlement",
         idea_caption="Knowledge builds life support",
         stakes_labels=["Resignation", "Stasis"],
         arc=("Cosmic insignificance", "Universal constructors", "Knowledge-limited only"),
         lesson="Anything physics permits, knowledge achieves", outcome="People are the significant entities",
         strategies=["Reject mediocrity", "See built life-support", "Reframe as knowledge",
                     "Ask what knowledge unlocks", "Aim past the given", "Conjecture the first step"],
         warnings=["We're-just-scum talk", "Protect-the-biosphere stasis", "Ambition capped", "Given mistaken for fixed"]),
    dict(slug="ch-04-creation", num=4, title="Creation",
         move="Run Real Variation and Selection",
         problem="a sealed bucket labeled knowledge waiting to be filled from an outside authority, staying empty",
         problem_labels=["Knowledge poured in", "Creationism"],
         episode="a branching tree of varied forms, failures pruned away, survivors carrying knowledge forward",
         idea_caption="Variation plus selection",
         stakes_labels=["No novelty", "Polished sameness"],
         arc=("Knowledge transmitted", "Conjecture and criticism", "Knowledge created"),
         lesson="Evolution and thought create, never copy", outcome="Two engines, one process",
         strategies=["Generate real variants", "Kill by criticism", "Never instruct from outside",
                     "Guard both halves", "Audit what you killed", "Reject bucket theories"],
         warnings=["One idea polished forever", "Nothing ever killed", "Politics not criticism", "Learning-from-outside myth"]),
    dict(slug="ch-05-reality-of-abstractions", num=5, title="The Reality of Abstractions",
         move="Explain at the Right Level",
         problem="a wall of atoms offered as the explanation for everything, explaining nothing in particular",
         problem_labels=["Reductionism", "Nothing-but atoms"],
         episode="a vast domino array computing primality, one output domino standing because a number is prime",
         idea_caption="641 is prime causes it",
         stakes_labels=["Wrong-level fixes", "Hidden causes"],
         arc=("Reductive hierarchy", "Explanatory pluralism", "Real abstractions"),
         lesson="Abstractions cause physical effects", outcome="Real = indispensable to explanation",
         strategies=["Find the real level", "Treat abstractions as real", "Target incentive bugs",
                     "Resist nothing-but talk", "Match fix to level", "Honor emergence"],
         warnings=["Fixing at wrong level", "It's-just-atoms", "Morale dismissed", "Cause hidden below"]),
    dict(slug="ch-06-jump-to-universality", num=6, title="The Jump to Universality",
         move="Ask Whether It Has Jumped",
         problem="a staircase of small parochial improvements ending abruptly at one final threshold step glowing gold",
         problem_labels=["Incremental", "Then a jump"],
         episode="a brass mechanical computer of gears embodying universal computation, unrecognized by its makers",
         idea_caption="The Analytical Engine jumped",
         stakes_labels=["Wasted reach", "Unseen potential"],
         arc=("Gradual improvement", "The threshold crossed", "Universal capability"),
         lesson="Parochial tools cross to universality", outcome="Value detaches from intended purpose",
         strategies=["Test for the jump", "Exploit latent reach", "Spot chosen parochialism",
                     "Ask beyond your purpose", "Pair digital with error-correction", "Mind your model bottleneck"],
         warnings=["Universal used parochially", "Roman-numeral choices", "Gradualist blindness", "Reach unexploited"]),
    dict(slug="ch-07-artificial-creativity", num=7, title="Artificial Creativity",
         move="Judge Understanding, Not Output",
         problem="an enormous lookup table producing fluent answers with an empty space where explanation should be",
         problem_labels=["Mimicry", "No origination"],
         episode="a glowing question mark inside a machine sparking a genuinely new explanation nobody programmed",
         idea_caption="Creativity: the unsolved problem",
         stakes_labels=["Fooled by fluency", "Denied on principle"],
         arc=("Behavior judged", "Explanation required", "AGI as person"),
         lesson="AGI needs a theory of creativity", outcome="A person, with full moral status",
         strategies=["Design mimicry tests", "Seek origination", "Value real capability",
                     "Watch for good disobedience", "Avoid Turing-test traps", "Hold humility both ways"],
         warnings=["Personhood on fluency", "Impossible-on-principle", "Capability extrapolated", "Black-box worship"]),
    dict(slug="ch-08-window-on-infinity", num=8, title="A Window on Infinity",
         move="Sort Unbounded from Bounded",
         problem="a hotel sign reading NO VACANCY while infinitely many lit rooms stretch beyond the horizon",
         problem_labels=["Full isn't full", "Finite intuition"],
         episode="Hilbert's infinite hotel shuffling guests upward, opening infinite rooms from a full house",
         idea_caption="The Infinity Hotel",
         stakes_labels=["False scarcity", "Mixed-up bounds"],
         arc=("Finite intuition", "Infinity's discipline", "Beginning of infinity"),
         lesson="Infinity has exact structure", outcome="We are always at the beginning",
         strategies=["Question finite bounds", "Sort your constraints", "Unbound the conjectures",
                     "Budget the bounded", "Watch the measure problem", "Stay early-minded"],
         warnings=["Running-out arguments", "Idea-space treated scarce", "Bounds confused", "Anything-goes infinity"]),
    dict(slug="ch-09-optimism", num=9, title="Optimism",
         move="Rewrite Evils as Knowledge Gaps",
         problem="a prophet confidently declaring a fixed doomed future while ignoring the one growing variable, knowledge",
         problem_labels=["Prophecy", "Fixed knowledge"],
         episode="a sky survey detecting an incoming asteroid in time, turning a natural disaster into a solved problem",
         idea_caption="Spaceguard: evils are knowledge gaps",
         stakes_labels=["Doom authority", "Static resignation"],
         arc=("Prophecy of doom", "Knowledge-gap framing", "Solvable problems"),
         lesson="All evils are insufficient knowledge", outcome="Problems inevitable, and soluble",
         strategies=["Write the knowledge gap", "Ban prophecy", "Fund your Spaceguard",
                     "Expect problems", "Build error-correction", "Refuse both blind stances"],
         warnings=["Confident doom", "Bounding future knowledge", "Blind optimism", "Stasis as safety"]),
    dict(slug="ch-10-dream-of-socrates", num=10, title="A Dream of Socrates",
         move="Treat Every Handoff as a Conjecture",
         problem="a funnel labeled teaching trying to pour knowledge into a head, the knowledge spilling uselessly away",
         problem_labels=["Transmission myth", "Poured-in knowledge"],
         episode="two speakers connected by dotted guess-lines, meaning reconstructed and productively mutated between them",
         idea_caption="Communication is conjecture",
         stakes_labels=["Silent misreads", "Authority frozen"],
         arc=("Knowledge transmitted", "Meaning conjectured", "Learner reconstructs"),
         lesson="No one transmits knowledge, only prompts it", outcome="Misunderstanding can create",
         strategies=["Add teach-back loops", "Harvest good misreads", "Find your Forms",
                     "Prompt, don't pour", "Criticize all authority", "Expect reconstruction"],
         warnings=["Assumed transmission", "Authority beyond criticism", "No feedback loop", "Misreads buried"]),
    dict(slug="ch-11-the-multiverse", num=11, title="The Multiverse",
         move="Take the Best Explanation Literally",
         problem="a physicist covering equations with a SHUT UP AND CALCULATE sign, refusing to say what they mean",
         problem_labels=["Instrumentalism", "Meaning refused"],
         episode="a single photon shown as fungible instances in parallel histories, splitting and interfering",
         idea_caption="Differentiating histories",
         stakes_labels=["Realism lost", "Magic collapse"],
         arc=("Prediction-recipe", "Explanation literal", "Multiverse realism"),
         lesson="Quantum theory describes parallel histories", outcome="No collapse, just differentiation",
         strategies=["Believe the best model", "Follow what follows", "Track differentiation",
                     "Drop it's-just-a-tool", "Reconceive probability", "State the implications"],
         warnings=["Shut-up-and-calculate", "Implications refused", "Intuition protected", "Collapse magic"]),
    dict(slug="ch-12-bad-philosophy", num=12, title="Bad Philosophy",
         move="Flag Question-Forbidding Doctrines",
         problem="a heavy door labeled DO NOT ASK bolted across a corridor of unexplored questions",
         problem_labels=["Blocks knowledge", "Forbids questions"],
         episode="a bright new explanation being shrugged into exile while an authoritative doctrine bars the debate",
         idea_caption="Doctrine that prevents debate",
         stakes_labels=["Fields captured", "Progress halted"],
         arc=("Harmless-philosophy myth", "Philosophy as infrastructure", "Criticism reopened"),
         lesson="Some philosophy actively blocks knowledge", outcome="Good philosophy opens problems",
         strategies=["Find forbidden questions", "Test we're-just-practical", "Spot hardened simplifications",
                     "Reopen the debate", "Criticize the doctrine", "Apply the symmetric test"],
         warnings=["That's-not-measurable", "Criticism-immunity", "Doctrine past its use", "Questions punished"]),
    dict(slug="ch-13-choices", num=13, title="Choices",
         move="Optimize for Error-Correction",
         problem="an elaborate machine averaging fixed preferences, jamming on a cycle it cannot resolve",
         problem_labels=["Preference aggregation", "Paradox jam"],
         episode="a governance mechanism swiftly removing a bad policy and reversing course without upheaval",
         idea_caption="Remove bad policies fast",
         stakes_labels=["Coherence lost", "Cynicism"],
         arc=("Aggregate preferences", "Correct errors", "Reversible decisions"),
         lesson="Decisions are problem-solving, not aggregation", outcome="Good systems remove bad choices fast",
         strategies=["Optimize error-removal", "Treat preferences as conjectures", "Favor reversibility",
                     "Assign clear ownership", "Ask how to undo", "Create new options"],
         warnings=["Fair-mirror obsession", "Preferences as fixed", "Slow reversal", "Consensus theater"]),
    dict(slug="ch-14-why-flowers-are-beautiful", num=14, title="Why Flowers Are Beautiful",
         move="Test Quality Across the Widest Gap",
         problem="a designer shrugging it's-all-subjective while an objectively striking bloom sits ignored",
         problem_labels=["Beauty as arbitrary", "In the eye only"],
         episode="a flower and a bee signaling across an unbridgeable species gap using hard-to-fake criteria",
         idea_caption="Objective cross-species beauty",
         stakes_labels=["Quality abandoned", "Fashion only"],
         arc=("Beauty subjective", "Signal across a gap", "Objective beauty"),
         lesson="Some beauty must be objective to work", outcome="Quality survives the widest gap",
         strategies=["Separate fashion from quality", "Signal across gaps", "Seek objective quality",
                     "Make signals hard to fake", "Test on distant audiences", "Discover, don't assign"],
         warnings=["It's-all-subjective", "Local fashion mistaken", "Easy-to-fake signals", "Quality unsought"]),
    dict(slug="ch-15-evolution-of-culture", num=15, title="The Evolution of Culture",
         move="Ask How Your Ideas Survive",
         problem="a sealed society of identical figures repeating one frozen pattern, dissent extinguished",
         problem_labels=["Anti-rational memes", "Criticism disabled"],
         episode="two idea-organisms: one thriving by usefulness under scrutiny, one surviving by silencing its critics",
         idea_caption="Rational vs anti-rational memes",
         stakes_labels=["Frozen progress", "Crushed creativity"],
         arc=("Static society", "Criticism transmitted", "Dynamic society"),
         lesson="Ideas survive by truth or by silencing critics", outcome="Meme-type decides the society",
         strategies=["Ask why ideas survive", "Answer the question", "Transmit criticism",
                     "Reward the questioner", "Spot disabled critique", "Guard the dynamic culture"],
         warnings=["Questioner punished", "We've-always-done-it", "Conclusions transmitted", "Quiet mistaken for health"]),
    dict(slug="ch-16-evolution-of-creativity", num=16, title="The Evolution of Creativity",
         move="See Learning as Creative Reconstruction",
         problem="a paradox symbol: a change-hostile tribe somehow producing the faculty that creates all change",
         problem_labels=["Static societies", "Yet creative minds"],
         episode="a learner inferring the hidden unspoken rules behind a group's behavior by conjecture and correction",
         idea_caption="Creativity for faithful transmission",
         stakes_labels=["Conformity engine", "Creativity conscripted"],
         arc=("Creativity for innovation?", "Creativity for transmission", "Redirected by Enlightenment"),
         lesson="Creativity evolved to acquire culture", outcome="Later turned toward innovation",
         strategies=["See learning as creative", "Reconstruct hidden rules", "Then criticize them",
                     "Reward improvement", "Free creativity from conformity", "Turn it outward"],
         warnings=["Absorption assumed passive", "Creativity for conformity", "Rules never criticized", "Faculty conscripted"]),
    dict(slug="ch-17-unsustainable", num=17, title="Unsustainable",
         move="Build Problem-Solving Capacity",
         problem="a civilization frozen in a fixed steady state, defenseless as an unforeseen problem arrives",
         problem_labels=["Sustainability as stasis", "Fragile balance"],
         episode="a dynamic society meeting a new crisis by rapidly creating knowledge, shattering a Malthusian ceiling",
         idea_caption="Dynamism, not stasis",
         stakes_labels=["Fragile collapse", "Foreclosed options"],
         arc=("Reach a stable state", "Continual problem-solving", "Dynamic survival"),
         lesson="Static stability is the fragile strategy", outcome="Safety is problem-solving capacity",
         strategies=["Reframe stable-state goals", "Build adaptability", "Extend means by knowledge",
                     "Expect new problems", "Weigh the asymmetry", "Reserve capacity, not just resources"],
         warnings=["Stable-end-state goals", "Stockpiling only", "Restraint over knowledge", "Irreversible thresholds ignored"]),
    dict(slug="ch-18-beginning", num=18, title="The Beginning",
         move="Treat Your Field as Just Beginning",
         problem="a candle of criticism flickering alone in a vast dark plain of frozen static cultures",
         problem_labels=["Enlightenment infancy", "Fragile, abortable"],
         episode="an unbounded upward horizon of open-ended progress, a single candle guarding the tradition of criticism",
         idea_caption="At the beginning of infinity",
         stakes_labels=["Progress aborted", "Drift to stasis"],
         arc=("History near-complete?", "History barely begun", "Sustain the tradition"),
         lesson="We are at the beginning of infinity", outcome="Unlimited, but only if sustained",
         strategies=["Treat your field as early", "Transmit criticism", "Guard error-correction",
                     "Resist stable-end-states", "Defend the dynamic tradition", "Choose progress"],
         warnings=["We're-nearly-done", "Conditions of criticism decaying", "Stasis tempting", "Progress assumed automatic"]),
]

def start_prompt(c):
    return (f"Infographic, three vertical editorial panels. Top banner: dark navy bar with "
        f"\"CHAPTER {c['num']}\" in a gold box and title \"{c['title'].upper()}\" in large cream serif capitals. "
        f"LEFT panel header \"THE PROBLEM\": flat illustration of {c['problem']}, two small gold label boxes: "
        f"\"{c['problem_labels'][0]}\" and \"{c['problem_labels'][1]}\". "
        f"CENTER panel header \"THE IDEA\": symbolic flat illustration (no people) of {c['episode']}, caption "
        f"\"{c['idea_caption']}\" beneath in gold serif. "
        f"RIGHT panel header \"THE STAKES\": illustration of the cost, two dark label boxes: "
        f"\"{c['stakes_labels'][0]}\" and \"{c['stakes_labels'][1]}\". "
        f"Bottom: gold label \"CORE MOVE\" then wide navy arrow containing \"{c['move'].upper()}\" in cream capitals. " + STYLE)

def end_prompt(c):
    return (f"Infographic dashboard. Top: dark navy header bar, gold \"CHAPTER {c['num']}\" then "
        f"\"{c['title'].upper()} — THE SHIFT\" in cream serif capitals. "
        f"LEFT section \"THE ARC\": three circles connected by curved arrows — navy circle \"BEFORE: {c['arc'][0]}\", "
        f"gold circle \"SHIFT: {c['arc'][1]}\", coral circle \"AFTER: {c['arc'][2]}\". "
        f"CENTER section \"THE IDEA\" in a gold-bordered card: small symbolic vignette (no people) of {c['idea_caption']}, "
        f"gold tag \"INSIGHT\" with text \"{c['lesson']}\", gold tag \"OUTCOME\" with text \"{c['outcome']}\". "
        f"RIGHT section \"PRACTICE CARDS\": six white cards in a 2x3 grid, each a simple line icon and a short label: "
        + ", ".join(f"\"{x}\"" for x in c["strategies"]) + ". "
        f"BOTTOM row \"WATCH FOR\": four red flag icons with labels "
        + ", ".join(f"\"{x}\"" for x in c["warnings"]) + ". " + STYLE)

def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--only"); ap.add_argument("--force", action="store_true")
    a = ap.parse_args(); fails = []
    for c in CH:
        if a.only and c["slug"] != a.only: continue
        for kind, p in (("start", start_prompt(c)), ("end", end_prompt(c))):
            out = OUTDIR / f"{c['slug']}-{kind}.png"
            if not gen(p, out, a.force): fails.append(out.name)
    print(f"\ndone. failures: {fails or 'none'}"); return 1 if fails else 0

if __name__ == "__main__":
    sys.exit(main())
